# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Asus\Desktop\HDA\Semester_2\SDHD\Lab\SDHD_Lab5\Software\Lab03_Lab04\Motion_Detection.cydsn\Motion_Detection.cyprj
# Date: Thu, 04 Jul 2024 11:14:52 GMT
#set_units -time ns
create_clock -name {ADC_DelSig_1_Ext_CP_Clk(routed)} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dclk_0}]]
create_clock -name {WaveDAC8_1_DacClk(routed)} -period 66666.666666666657 -waveform {0 33333.3333333333} [list [get_pins {ClockBlock/dclk_2}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_clock -name {ADC_DelSig_1_Ext_CP_Clk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {UART_1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 27 53} -nominal_period 1083.3333333333333 [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {ADC_DelSig_1_theACLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 189 377} [list [get_pins {ClockBlock/aclk_glb_0}]]
create_generated_clock -name {WaveDAC8_1_DacClk} -source [get_pins {ClockBlock/clk_sync}] -edges {1 1601 3199} -nominal_period 66666.666666666657 [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {Clock_Debouncer} -source [get_pins {ClockBlock/clk_sync}] -edges {1 240001 480001} [list [get_pins {ClockBlock/dclk_glb_3}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\Asus\Desktop\HDA\Semester_2\SDHD\Lab\SDHD_Lab5\Software\Lab03_Lab04\Motion_Detection.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Asus\Desktop\HDA\Semester_2\SDHD\Lab\SDHD_Lab5\Software\Lab03_Lab04\Motion_Detection.cydsn\Motion_Detection.cyprj
# Date: Thu, 04 Jul 2024 11:14:48 GMT
